## What Is A Python Numpy Array?
You already read in the introduction that NumPy arrays are a bit like Python lists, but still very much different at the same time. For those of you who are new to the topic, let’s clarify what it exactly is and what it’s good for.

As the name kind of gives away, a NumPy array is a central data structure of the numpy library. The library’s name is actually short for “Numeric Python” or “Numerical Python”.

This already gives an idea of what you’re dealing with, right?

In other words, NumPy is a Python library that is the core library for scientific computing in Python. It contains a collection of tools and techniques that can be used to solve on a computer mathematical models of problems in Science and Engineering. One of these tools is a high-performance multidimensional array object that is a powerful data structure for efficient computation of arrays and matrices. To work with these arrays, there’s a huge amount of high-level mathematical functions operate on these matrices and arrays.

In [1]:
#import numpy library
import numpy as np

In [2]:
my_array = np.array([1,2,3,4,5])
my_2d_array = np.array([[1,2],[8,9]])
my_3d_array = np.arange(12).reshape(2,2,3)
# Print the array
print("1d_array: ")
print(my_array)

# Print the 2d array
print("2d_array: ")
print(my_2d_array)

# Print the 3d array
print("3d_array: ")
print(my_3d_array)

1d_array: 
[1 2 3 4 5]
2d_array: 
[[1 2]
 [8 9]]
3d_array: 
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


##  Data, shape, dtype
* The data pointer indicates the memory address of the first byte in the array,
* The data type or dtype pointer describes the kind of elements that are contained within the array,
* The shape indicates the shape of the array, and

In [3]:
# Print out memory address
print(my_2d_array.data)

# Print out the shape of `my_array`
print(my_2d_array.shape)

# Print out the data type of `my_array`
print(my_2d_array.dtype)

# Print out the stride of `my_array`
print(my_2d_array.strides)

(2, 2)
int64
(16, 8)


## Properties

In [4]:
# Create an array of ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
# Create an array of zeros
np.zeros((2,3,4),dtype=np.int16)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int16)

In [6]:
# Create an array with random values
np.random.random((2,2))

array([[0.42024479, 0.24312244],
       [0.23548695, 0.40935339]])

In [7]:
# Create an empty array
np.empty((3,2))


array([[0.00000000e+000, 6.94994233e-310],
       [5.39489646e-317, 5.39488065e-317],
       [1.02277546e-259, 2.70003634e-316]])

In [8]:
# Create a full array
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [9]:
# Create an array of evenly-spaced values
np.arange(10,25,5)

array([10, 15, 20])

In [10]:
# Create an array of evenly-spaced values
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

## How NumPy Broadcasting Works
Before you go deeper into scientific computing, it might be a good idea to first go over what broadcasting exactly is: it’s a mechanism that allows NumPy to work with arrays of different shapes when you’re performing arithmetic operations.

To put it in a more practical context, you often have an array that’s somewhat larger and another one that’s somewhat smaller. Ideally, you want to use the smaller array multiple times to perform an operation (such as a sum, multiplication, etc.) on the larger array.

To do this, you use the broadcasting mechanism.

However, there are some rules if you want to use it. And, before you already sigh, you’ll see that these “rules” are very simple and kind of straightforward!

* First off, to make sure that the broadcasting is successful, the dimensions of your arrays need to be compatible. Two dimensions are compatible when they are equal. Consider the following example:

In [46]:
# Initialize `x`
x = np.ones((3,4))

# Check shape of `x`
print(x.shape)

# Initialize `y`
# y = np.random.random((3,4))
y = np.ones((1,4))
# Check shape of `y`
# print(y.shape)
print(x)
print(y)

# Add `x` and `y`
x + y

(3, 4)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]]


array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [52]:
import numpy as np

# Initialize `x`
x = np.ones((3,4))

# Check shape of `x`
print(x.shape)

# Initialize `y`
y = np.ones((1,4))

# Check shape of `y`
print(y.shape)

# Subtract `x` and `y`
x + y 

(3, 4)
(1, 4)


array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [53]:
x + 1

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [54]:
x * 2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [55]:
x/2

array([[0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5]])

In [56]:
print(x.shape)
y = np.arange(3).reshape(3,1)
print(y)
print(y.shape)

(3, 4)
[[0]
 [1]
 [2]]
(3, 1)


In [17]:
x + y

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [67]:
w = np.array([[1,2,3]])
print(w)
print(w.shape)
x = np.ones((4,3))
print(x)
print(x.shape)
print(x+w)

[[1 2 3]]
(1, 3)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(4, 3)
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


## How Do Array Mathematics Work?
* You’ve seen that broadcasting is handy when you’re doing arithmetic operations. In this section, you’ll discover some of the functions that you can use to do mathematics with arrays.

* As such, it probably won’t surprise you that you can just use +, -, *, / or % to add, subtract, multiply, divide or calculate the remainder of two (or more) arrays. However, a big part of why NumPy is so handy, is because it also has functions to do this. The equivalent functions of the operations that you have seen just now are, respectively, np.add(), np.subtract(), np.multiply(), np.divide() and np.remainder().

* You can also easily do exponentiation and taking the square root of your arrays with np.exp() and np.sqrt(), or calculate the sines or cosines of your array with np.sin() and np.cos(). Lastly, its’ also useful to mention that there’s also a way for you to calculate the natural logarithm with np.log() or calculate the dot product by applying the dot() to your array.

In [70]:
#Note : x*y and x.dot(y)
x = np.arange(9).reshape(3,3)
y = np.arange(3).reshape(3,1)
print("x :\n",x)
print("y :\n",y)
print("x*y = \n",x*y)
print("x*y matrix = \n", np.dot(x, y))
# Không nhân ma trận
# print("x.dot(y) = \n",x.dot(y))


x :
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
y :
 [[0]
 [1]
 [2]]
x*y = 
 [[ 0  0  0]
 [ 3  4  5]
 [12 14 16]]
x*y matrix = 
 [[ 5]
 [14]
 [23]]


* Something a little bit more advanced than subsetting, if you will, is slicing. Here, you consider not just particular values of your arrays, but you go to the level of rows and columns. You’re basically working with “regions” of data instead of pure “locations”.

You can see what is meant with this analogy in these code examples:

In [19]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [20]:
x[:]

array([1, 2, 3, 4, 5])

In [21]:
x[0:4]

array([1, 2, 3, 4])

In [22]:
x[:3]

array([1, 2, 3])

In [23]:
x[-1:]

array([5])

## How To Transpose Your Arrays
What transposing your arrays actually does is permuting the dimensions of it. Or, in other words, you switch around the shape of the array. Let’s take a small example to show you the effect of transposition:

In [24]:
my_2d_array = np.arange(6).reshape(2,3)
# Print `my_2d_array`
print(my_2d_array)

[[0 1 2]
 [3 4 5]]


In [73]:
# Transpose `my_2d_array`
print(np.transpose(my_2d_array))
# print(my_2d_array.T)

[[0 3]
 [1 4]
 [2 5]]


In [26]:
# Or use `T` to transpose `my_2d_array`
print(my_2d_array.T)

[[0 3]
 [1 4]
 [2 5]]


In [27]:
print(my_2d_array.shape)
print(my_2d_array.T.shape)

(2, 3)
(3, 2)


In [78]:
my_3d_array = np.arange(24).reshape(2,3,4)
print(my_3d_array)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
np.transpose(my_3d_array)

## Indexing
* Single element indexing

In [80]:
x = np.arange(10)
print(x)
print(x[2])

print(x[-2])

[0 1 2 3 4 5 6 7 8 9]
2
8


* Multiple element indexing

In [81]:
x.shape = (2,5) # now x is 2-dimensional
print(x)
x[1,3]

[[0 1 2 3 4]
 [5 6 7 8 9]]


8

* Other indexing options

In [82]:
x = np.arange(10)

In [83]:
x[2:5]

array([2, 3, 4])

In [84]:
x[:-7]

array([0, 1, 2])

In [85]:
x[1:7:2]

array([1, 3, 5])

In [86]:
y = np.arange(35).reshape(5,7)
print(y)
y[1:5:2,::3]

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


array([[ 7, 10, 13],
       [21, 24, 27]])

* Boolean or “mask” index arrays

In [87]:
y = np.array([16,17,19,20,21,22])
b = y>20
print(b)

y[b]

[False False False False  True  True]


array([21, 22])

In [91]:
y = np.arange(9).reshape(3,3)
print(y)

index = np.arange(3)
print(index)

mask = np.array([0,2,1])
print(mask)

y[index,mask]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]
[0 2 1]


array([0, 5, 7])

In [ ]:
# np.max (array, axis = 0: column, 1: row)
# np.argmax ()
# np.min
# np.argmin

In [105]:
# join
x = np.array([1,2,3,4])
y = np.ones([4])
z = np.concatenate((x, y))
print(z)
print(z.shape)

w = np.ones([4])
print(y)
print(w)


# v = np.vstack((y,w)) #vertical
# print(v)
h = np.hstack((y,w)) #horizental
print(h)



[1. 2. 3. 4. 1. 1. 1. 1.]
(8,)
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
# Gauss Jordan

def gaussJordan(A,b):
    b = np.shape([b, 0])
    
    